import { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import TrackList from "../../Components/TrackList";
import { Hoops } from "../../images";
import { Album, TrackInfo } from "../../typings";
import { fetchAlbums } from "../../utils/fetchAlbums";
import { fetchTrackInfo } from "../../utils/fetchTrackInfo";

type Props = {
  albums: Album[];
  trackInfo: TrackInfo[];
}


  
  export default function Tracks({ albums, trackInfo } : Props) {
    return (
      <div className='w-screen h-screen overflow-y-scroll overflow-hidden snap-y snap-mandatory z-0'>
        <Head>
          <title>K Pierre&apos;s World</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <section>
        <nav className='w-full z-10 sticky top-0'>
        <div className='flex justify-between items-center max-w-7xl mx-auto text-white p-8'>
            {/* Left section */}
            <div className='relative w-12 h-12 hover:cursor-pointer hover:animate-pulse'>
                <Link href='/'>
                    <Image src={Hoops} objectFit='contain' layout='fill' />
                </Link>
            </div>
            {/* Right section */}
            <ul className='flex space-x-4 text-2xl navigation'>
                <li>
                    <Link href='/'>
                        Return Home
                    </Link>
                </li>
            </ul>
        </div>
    </nav>
          <TrackList albums={albums} trackInfo={trackInfo} />
        </section>

  
      </div>
    )
  }

  export const getStaticProps: GetStaticProps<Props> = async () => {
    const albums: Album[] = await fetchAlbums();
    const trackInfo: TrackInfo[] = await fetchTrackInfo();
  
    return {
      props: {
        albums, 
        trackInfo
      },
  
      revalidate: 10,
    }
  }
  