import { GetStaticProps } from "next";
import Head from "next/head";
import Navbar_2 from "../../Components/Navbar_2";
import SongCard from "../../Components/SongCard";
import TrackCard from "../../Components/TrackCard";
import TrackList from "../../Components/TrackList";
import { Album, TrackInfo } from "../../typings";
import { fetchAlbums } from "../../utils/fetchAlbums";
import { fetchTrackInfo } from "../../utils/fetchTrackInfo";

type Props = {
  albums: Album[];
  trackInfo: TrackInfo[];
}


  
  export default function Tracks({ albums, trackInfo } : Props) {
    return (
      <div className='w-screen h-screen overflow-y-scroll overflow-hidden snap-y snap-mandatory z-0'>
        <Head>
          <title>K Pierre&apos;s World</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <section>
           <Navbar_2 />        
          <TrackList albums={albums} trackInfo={trackInfo} />
        </section>

  
      </div>
    )
  }

  export const getStaticProps: GetStaticProps<Props> = async () => {
    const albums: Album[] = await fetchAlbums();
    const trackInfo: TrackInfo[] = await fetchTrackInfo();
  
    return {
      props: {
        albums, 
        trackInfo
      },
  
      revalidate: 10,
    }
  }
  