import { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Contact from '../Components/Contact';
import Hero from '../Components/Hero';
import Music from '../Components/Music';
import Navbar_2 from '../Components/Navbar_2';
import Shop from '../Components/Shop';
import { Album, LatestTrack } from '../typings';
import { fetchAlbums } from '../utils/fetchAlbums'
import { fetchLatestTracks } from '../utils/fetchLatestTracks';

type Props = {
  albums: Album[];
  latestTracks: LatestTrack[];
}


export default function Home( {albums, latestTracks} : Props ) {
  return (
    <div className='w-screen h-screen overflow-y-scroll overflow-hidden snap-y snap-mandatory z-0'>
      <Head>
        <title>K Pierre&apos;s World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <section className='snap-start'>
        <Navbar_2 />
        <Hero />
      </section>

      <section id='music' className='snap-start md:snap-center'>
        <Music latestTracks={latestTracks} albums={albums} />
      </section>

      <section id='contact' className='snap-start md:snap-center'>
        <Contact />
      </section>

      <section id='shop' className='snap-start md:snap-center'>
        <Shop />
      </section>

    </div>
  )
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const albums: Album[] = await fetchAlbums();
  const latestTracks: LatestTrack[] = await fetchLatestTracks();

  return {
    props: {
      albums,
      latestTracks
    },

    revalidate: 10,
  }
}